  
  common:
    socket:
      enabled: true
      port: 8818
    http:
      enabled: true
      port: 8804
    ws:
      enabled: true
      port: 8819
    log_mode: "debug"
    token: ""
  specific:
    eth_server: ""
    log_mode: "debug"