common:
  socket:
    enabled: true
    port: 8818
  http:
    enabled: true
    port: 8804
  ws:
    enabled: true
    port: 8819
  log_mode: "debug"
  token: ""
  enable_profiling: true
  profiling_port": 8874
specific:
  eth_server: "https://rpc.ankr.com/polygon_mumbai"
  log_mode: "debug"
