version: '3'
services:

  sai-storage:
    build:
      context: ./saiStorage
      dockerfile: Dockerfile
    ports:
      - "8801:8801"
      - "8802:8802"

  sai-web-socket:
    build:
      context: ./saiWebSocket
      dockerfile: Dockerfile
    ports:
      - "8820:8820"
    volumes:
      - ./saiWebSocket/build/saiwebsocket.config:/srv/saiwebsocket.config

  sai-eth-manager:
    build:
      context: ./saiEthManager
      dockerfile: Dockerfile
    ports:
      - "8819:8819"
    volumes:
      - ./saiEthManager/build/config.json:/srv/config.json

  sai-eth-indexer:
    build:
      context: ./saiEthIndexer
      dockerfile: Dockerfile
    ports:
      - "8817:8817"
    volumes:
      - ./saiEthIndexer/build/block.data:/srv/block.data
      - ./saiEthIndexer/build/config/config.json:/srv/config/config.json
      - ./saiEthIndexer/build/config/contracts.json:/srv/config/contracts.json