version: '3'
services:

#  sai-auth:
#    build:
#      context: ./saiAuth
#      dockerfile: Dockerfile
#    ports:
#      - "8888:8888"
#      - "8800:8800"
#      - "8803:8803"
#
#  sai-storage:
#    build:
#      context: ./saiStorage
#      dockerfile: Dockerfile
#    ports:
#      - "8801:8801"
#      - "8802:8802"

  sai-eth-interaction:
    build:
      context: ./saiEthInteraction
      dockerfile: Dockerfile
    ports:
      - "8818:8018"
      - "8819:8019"
      - "8804:8804"
    volumes:
      - ./saiContractExplorer/build/block.data:/srv/block.data
      - ./saiContractExplorer/build/config.json:/srv/config.json


